### ISSUE TITLE
unrecognized multiple matches in the grid search

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#111]
While investigating #110 I recognized that there are some multiple matches that are not filtered by fragment matching. It happens because they are not marked as multiple matching.

Currently the grid search finds multiple matching quants for one ident. But if the idents are close together it could happen that they are matched to the same quant entry, e.g.:

| |protein.Accession|protein.Description|protein.falsePositiveRate|peptide.mhp|peptide.seq|peptide.score|precursor.leID.ident|precursor.mhp|precursor.retT|precursor.inten|precursor.z|precursor.mz|precursor.Mobility|predictedRt|sdRt|matchedEMRTs|spectrumID|rt_min|mwHPlus|Intensity|matched.quant.spectrumIDs|precursor.leID.quant|idSource|synapterPlgsAgreement|FragmentMatching|
|---|-----------------|-------------------|-------------------------|-----------|-----------|-------------|--------------------|-------------|--------------|---------------|-----------|------------|------------------|-----------|----|------------|----------|------|-------|---------|-------------------------|--------------------|--------|---------------------|----------------|
|16207|P20338|Ras-related protein Rab-4A OS=Homo sapiens GN=RAB4A PE=1 SV=3|0.0009|700.4352|IINVGGK|6.7113|16207|700.4373|34.6481|6548|1|700.4373|86894|33.8821990348665|0.500659446260807|1|8343|35.0009|700.4378|306942|8343|8343|transfer|agree|2|
|25330|P27797|Calreticulin OS=Homo sapiens GN=CALR PE=1 SV=1|0|700.4352|NVLINK|7.9979|25330|700.4398|34.7458654449727|12028|1|700.4398|87102|35.2292622234454|0.544438607361508|1|8343|35.0009|700.4378|306942|8343|NA|transfer|no_plgs_id|6|

The current implementation of the most functions (even `fragmentMatching`) don't handle this case (multiple ident vs one quant; just the other way around (one ident vs multiple quants)). 
I am unsure whether we could improve this situation by modifying the `fragmentMatching` alone. Maybe we have to modify the grid search. 

BTW `fragmentMatching` would prefer the second entry because of 6 common peaks (vs 2 for the first one) but PLGS has identified the first:

![dup1](https://cloud.githubusercontent.com/assets/1828443/12928425/a8b68510-cf6d-11e5-8216-e891c2ff0939.png)
![dup2](https://cloud.githubusercontent.com/assets/1828443/12928431/ac304cf8-cf6d-11e5-9b08-62effa6745c5.png)

I will look at the grid search the next days whether we could avoid such events.

@pavel-shliaha any comments?

In @pavel-shliaha test set there are 90 pairs (181 duplicated matches, in one case there are three idents vs one quant) out of 24000 ident and 11500 quant entries.

**Comment by pavel-shliaha** [comment]
@sgibb sorry for the delay in reply. This is not unexpected and I would not worry about it or change synapter functionality in any major way. If you relax the thresholds more you will see more of such instances. I would also expect the number of such instances to be very small (which is what you see). I would suggest the following:

1) after matching (including fragment matching) delete EMRTs that match the same peptide and write "EMRT_matched_to_multiple_Ident_peptides"  
2) "(to be honest as human I wouldn't match any of them because the look very different)" dont be such a human ))). Please note that these spectra that you see are NOT spectra of individual peptides, they are composite spectra of hundreds of peptides! You will see lots of spectra with unassigned fragments. Thus I would match spectrum 2 as correct one.

**Comment by sgibb** [comment]
> 1) after matching (including fragment matching) dont delete EMRTs that match the same peptide and write "EMRT_matched_to_multiple_Ident_peptides" in "Counts" column of the matched EMRTs data.frame

We can't do this. `Counts` is a `numeric` column. We could set `Counts` `NA` (or remove the entries completely). Or we introduce yet another column `EMRT_matched_to_multiple_Ident_peptides` with `TRUE/FALSE` (that would be again another often useless column).

**Comment by pavel-shliaha** [comment]
NA is good enough for me

**Comment by sgibb** [comment]
There is a new method `filterNonUniqueIdentMatches` now, that set all these `Counts` to `NA`, adds a new column, namely `matchedMultipleIdentEMRTs` (with `TRUE`/`FALSE`) and set the content of the column `synapterPlgsAgreement` to `multiple_ident_matches`.
