### ISSUE TITLE
problems with master construction

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#113]
@sgibb I get the following message trying to construct master:

Generating unique proteotypic peptides...
Error in duplicated(x) : object '.peptides' not found

the R script is in 

Y:\RAW\pvs22\_QTOF_DATA_data3\synapter2paper\kuharev2015\bugs_investigation\master_construction_bug

the R script references all the files necessary

**Comment by pavel-shliaha** [comment]
sorry now synapter fails to update

Warning: package 'BiocParallel' was built under R version 3.2.3
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "externalRefMethod" of class "expressionORfunction"; definition not updated
Warning in .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "externalRefMethod" of class "functionORNULL"; definition not updated
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.2.1/library/synapter'
* restoring previous 'C:/Program Files/R/R-3.2.1/library/synapter'
Error: Command failed (1)

**Comment by sgibb** [comment]
Are you sure you tried to install synapter 2.0 via `devtools::install_github("lgatto/synapter@2.0")`? Synapter 2.0 doesn't depend on BiocParallel anymore so this warning makes no sense to me. BTW would it be possible to update your R installation to R-3.2.4? 3.2.1 is quite old (> 9 month).

**Comment by pavel-shliaha** [comment]
sorry guys forgot to specify quick = TRUE
