### ISSUE TITLE
synergize2 needed?

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#119]
In synapter 1 we had a `synergize` function to run the typical workflow and generating a report. Should we provide a similar method `synergize2` for the new synapter including 3d grid search, fragment matching etc.?

Or should we remove even the old `synergize` and let the user build his own workflow?

**Comment by lgatto** [comment]
Yes, I would suggest a `synapter2` function is the way forward because
1. It is easier to start from scratch rather then modifying an existing function.
2. We keep implicit backward compatibility.
