### ISSUE TITLE
modelIntensity and correctIntensities is counterintuitive

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#126]
The current workflow using `modelIntensity` and `correctIntensities` is counterintuitive.
While `modelRt` build the rt model and corrects the retention times the `modelIntensity` functions just creates the model and a new column `intensityCorrectionFactor`. In contrast to the rt correction the user has to apply the `correctIntensities` functions manually on a `MSnSet`:
```r
# synapter workflow
# ...

modelIntensity(synapterObj)

msnset <- as(synapterObj, "MSnSet")

## do stuff with msnset

correctedMSnSet <- correctIntensities(msnset)
```

I would suggest to correct the intensities automatically, create the `intensityCorrectionFactor` column and if the user wants to `requantifiy` the intensity correction could be undone and redone afterwards:

```r
# synapter workflow
# ...

modelIntensity(synapterObj)
# and run: intensity = intensity * intensityCorrectionFactor 

msnset <- as(synapterObj, "MSnSet")

requantify(msnset, ...)
# intensity = intensity / intensityCorrectionFactor
# requantify
# intensity = intensity * intensityCorrectionFactor
```

This approach would completely remove the need to call `correctIntensities` manually (in the same manner as nobody needs to call `correctRetentionTimes`). IMHO the uncorrected intensities are just useful for `requantify`. 

What is your opinion @pavel-shliaha ?

**Comment by pavel-shliaha** [comment]
very nice thinking! I completely agree with that!
