### ISSUE TITLE
issue with synergise

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#129]
Getting the following issue with synergise now, after installing the new verison:

Quitting from lines 263-287 (synergise2.Rmd) 
Error in parse(text = x, srcfile = src) : <text>:6:71: unexpected ']'
5: if (!is.na(selCommon)) {
6:   common <- fragmentMatchingStats$unique[selCommon, c("ncommon", "fdr"]
                                                                         ^

the code and data are in:

Y:\RAW\pvs22\_QTOF_DATA_data3\synapter2paper\kuharev2015\bugs_investigation\NP_vs_S2

the code is under name "compare_synergise_and_explicit.R"

**Comment by sgibb** [comment]
sry, copy&paste error, fixed
