### ISSUE TITLE
grid search bug

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#134]
In the LOPIMS dataset one of the analysis fails with the following problem:

```
searchGrid(synapterAnalysis, 
               imdiffs = Inf, ppm = seq (2, 20, 2),
               nsd = seq (0.5, 5, 0.5))

```
> Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)

I can then execute plotGrid(), but 
    
`setBestGridParams (synapterAnalysis)`

produces the following error:
  
>Error in `rownames<-`(`*tmp*`, value = c("nsd", "ppm", "imdiff")) : 
  attempt to set 'rownames' on an object with no dimensions

The code is in:

`Y:\RAW\pvs22\_QTOF_DATA_data3\synapter2paper\kuharev2015\bugs_investigation\seBestGridParams_bug`

please have a look

**Comment by sgibb** [comment]
This happens for some `ppm == 20`. There seems to be a problem in summarising the results of the grid search:
```r
searchGrid(synapterAnalysis, imdiffs=Inf, ppm=c(18, 20), nsds=seq(0.5, 5, by=0.5))
lengths(synapterAnalysis$GridDetails) # should be always 5
# 0.5:18:Inf 0.5:20:Inf   1:18:Inf   1:20:Inf 1.5:18:Inf 1.5:20:Inf   2:18:Inf   2:20:Inf 2.5:18:Inf 2.5:20:Inf
#          5          5          5          5          5          5          5          6          5          6
#   3:18:Inf   3:20:Inf 3.5:18:Inf 3.5:20:Inf   4:18:Inf   4:20:Inf 4.5:18:Inf 4.5:20:Inf   5:18:Inf   5:20:Inf
#          5          7          5          7          5          7          5          7          5          5
synapterAnalysis$GridDetails[15:18]
# $`4:18:Inf`
#   -2   -1    0    1    2
#    9    1    1  283 6405
#
# $`4:20:Inf`
#   -2   -1    0    1    2 <NA> <NA>
#    4    0    0    0    0  245 6450
#
# $`4.5:18:Inf`
#   -2   -1    0    1    2
#    8    1    1  246 6443
#
# $`4.5:20:Inf`
#   -2   -1    0    1    2 <NA> <NA>
#    3    0    0    0    0  213 6483
#
```

**Comment by sgibb** [comment]
Ok this always happens if a category with a lower index (a category on the left hand size) has zero matches and the next higher category has at least one match, e.g.
Category -2 (multiple mismatches): 0
Category -1 (one mismatch): 1 => warning in `searchGrid` and error later in `setBestGridParams`.
