### ISSUE TITLE
synapter 1.99 fails to build on bioc

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#136]
Dear @lgatto, it seems that some files for the vignette are missing. Could you please have a look:
https://bioconductor.org/checkResults/devel/bioc-LATEST/synapter/
```
   ‘fragmentmatching.Rmd’ using ‘UTF-8’ 
Warning in readLines(if (is.character(input2)) { :
  cannot open file './Foreword.md': No such file or directory
Quitting from lines 37-37 (./Foreword.md) 
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
```

**Comment by lgatto** [comment]
Strange???
![2017-04-07-074600_771x322_scrot](https://cloud.githubusercontent.com/assets/384198/24788601/48da00cc-1b66-11e7-8de7-5ab2f7a66122.png)

**Comment by lgatto** [comment]
These files are not copied into `inst/docs`, hence the error.

**Comment by lgatto** [comment]
The files are currently duplicated, which is not nice. But I would prefer to have them in the `vignettes` directory, rather than (only) in `inst/doc`, but not sure how and why at the moment. Maybe renaming them `Rmd`, which will get them copied over?

**Comment by sgibb** [comment]
I am not convinced that copying the to `inst/doc` or renaming them into `Rmd` will solve the problem. I am not sure why it fails on bioc because locally and on [travis](https://travis-ci.org/lgatto/synapter/builds/219336832) it builds without copying/renaming.

**Comment by sgibb** [comment]
BTW it should be the same vignette setup as used in `MSnbase`.

**Comment by lgatto** [comment]
I tested the above locally, which is why I ended up committing to Bioc.

**Comment by lgatto** [comment]
I confirm that things check fine locally - no idea why/what on Bioc.

**Comment by lgatto** [comment]
`1.99.0` now builds - probably something on their side. I won't do any change now, but we should remove the files in `inst/doc` in the new release (unless things break before). Let's close this issue after the release.
