### ISSUE TITLE
misleading names

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#67]
Certain names that have been given to variables, columns, function, etc are misleading and need to be changed. I will keep adding them as I notice them. Please do not close this issue. Also change things as you see fit, i.e. if things sound ok to you dont change them. Below is a list of things to be changed:

- [x] in CrossMatching DF, there is a column called "matchType" for transfer type (e.g. unique-true). This needs to be changed, since peptide.matchType is also  a column to determine which identification category (pass of database search) the peptide belongs to.  
- [x] in CrossMatching DF change NAs in "matchType" column to "no_id_in_quant_run"
- [x] "create flat EMRTs data.frame" message in crossMatching function. I suggest "create dataframe: one matched EMRT per line"
- [x] "Function" which used to return the number of matched EMRTs in old synapter is misleading since P3D already contains Function column (1|2 depending on whether EMRT is a low or high energy). Instead suggest: "matched_EMRTs", "common_fragments", "matched_EMRTs_filetered", "PLGS_EMRT", where PLGS_EMRT is the number of EMRT if a peptide has been identified.

**Comment by sgibb** [comment]
`Function*` should be renamed to

`matchedEMRTs`
`matchedEMRTs.beforeFilterUniqueMatches`
`matchedEMRTs.beforeFilterNonUniqueMatches`
