### ISSUE TITLE
How to handle false positives produced by the grid search?

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#73]
This issue describes a problem @pavel-shliaha and I recognized a few weeks ago. It is mostly a quotation of our email conversation.

It sometimes happen that our gridSearch matches two EMRTs that are not matched by PLGS.

> It seems that the identification (library) peptide
with the `precursor.leID == 1158` matches two different entries of the Pep3D file
nearly perfectly: `spectrumID == c(23517, 23519)`. PLGS has chosen the guy with
the spectrumID 23519. The 3D grid search thinks 23517 would be the best match
(both the mass and the retention time are very similar but the ion mobility
differs obviously):

> ident (id/mass/retention time/ion mobility):
1158 1339.807 117.6523 98.925

> pep3d (id/mass/retention time/ion mobility):
23517 1339.808 123.9536 98.971
23519 1339.808 123.9566 90.870

> Because 23519 != 23517 it is reported as unique false match (the difference in ionmobility
98.925-90.870 is larger than the allowed 1.2 (imdiff) otherwise it would be a non-unique
false match).
The sequence is NA because 23517 was not identified by PLGS.
The traditional 2D grid search reports this as non-unique false (23517)
and non-unique true (23519) match. If you consider these results of the cross
matching (based on the 2D grid search) PLGS has chosen the best candidate because we have 12 common peaks for 1158 and 23519 vs. 6 common peaks for 1158 and 23517.

@pavel-shliaha suggest to remove such false positive matches. That means we would remove all *unique-false* matches. Therefore we need to introduce a new method, e.g. `removeFalsePositiveEMRTmatches`.
But we can only remove false positive matches that were identified in the identification and quantitation run (otherwise we don't know whether it is a false positive or true positive match).

**Comment by sgibb** [comment]
Now there is an internal function that checks the agreement. The result are following below (for one single run). @pavel-shliaha I am wondering how we handle multiple matches (generated by the gridSearch), e.g. row 1 and 3:
```r
emrts <- s$MatchedEMRTs[c("precursor.leID.ident", "precursor.leID.quant",
                          "matched.quant.spectrumIDs", "idSource")]
emrts <- .findSynapterPlgsAgreement(emrts)

select <- c(1:4, 14, 38, 152)

emrts[select,]
#     precursor.leID.ident precursor.leID.quant matched.quant.spectrumIDs idSource   synapterPlgsAgreement
# 1                  62976                55811               55811;56505   rescue          agree;disagree
# 2                  63067                55938                             rescue    no_synapter_transfer
# 3                    248                  233               233;281;450   rescue agree;disagree;disagree
# 4                  69282                61573                     61389 transfer                disagree
# 14                 52758                46879                     46879 transfer                   agree
# 38                 64241                   NA                     56929 transfer              no_plgs_id
# 152                67327                   NA                           transfer       no_id_or_transfer
```

**Comment by pavel-shliaha** [comment]
I would actually prefer agree;disagree;agree to be merged in one answer which is no_transfer (there is no transfer there in my opinion). Please see my comment from 10 November on how to calculate the metric for PLGS and synapter agreement.

**Comment by sgibb** [comment]
All multiple matches are merged to `no_synapter_transfer` now (currently only affecting a single run):
```r
emrts[select,]
#     precursor.leID.ident precursor.leID.quant matched.quant.spectrumIDs idSource synapterPlgsAgreement
# 1                  62976                55811               55811;56505   rescue  no_synapter_transfer
# 2                  63067                55938                             rescue  no_synapter_transfer
# 3                    248                  233               233;281;450   rescue  no_synapter_transfer
# 4                  69282                61573                     61389 transfer              disagree
# 14                 52758                46879                     46879 transfer                 agree
# 38                 64241                   NA                     56929 transfer            no_plgs_id
# 152                67327                   NA                           transfer     no_id_or_transfer
```

Is `no_synapter_transfer` correct for rescued EMRTs?

**Comment by sgibb** [comment]
Ok, it works for a single run. Now we need to combine the single runs into an `MSnSet` object. I used the `ups25a, ups25b, ..., ups50c` objects provided by `synapterdata` and processed them as described in the `synapter` vignette. After combining them via `combine` we get the following:
```r
f <- fData(ms)
agreeCol <- grepl("synapterPlgsAgreement", colnames(f))
tail(f[, agreeCol])
#            synapterPlgsAgreement.ups25a synapterPlgsAgreement.ups25b synapterPlgsAgreement.ups25c synapterPlgsAgreement.ups50a
# YEJL_ECODH                   no_plgs_id                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YFBU_ECODH                        agree                        agree                        agree                        agree
# YGFZ_ECODH                        agree                        agree                        agree                        agree
# YJGA_ECODH                        agree                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer                   no_plgs_id                   no_plgs_id
# ZAPB_ECODH                        agree                        agree                        agree                        agree
#            synapterPlgsAgreement.ups50b synapterPlgsAgreement.ups50c
# YEJL_ECODH                   no_plgs_id                   no_plgs_id
# YFBU_ECODH                        agree                        agree
# YGFZ_ECODH                        agree                        agree
# YJGA_ECODH                        agree                   no_plgs_id
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer
# ZAPB_ECODH                   no_plgs_id                        agree

tail(apply(f[, agreeCol], 1, table))
# $YEJL_ECODH
#
# no_plgs_id
#          6
#
# $YFBU_ECODH
#
# agree
#     6
#
# $YGFZ_ECODH
#
# agree
#     6
#
# $YJGA_ECODH
#
#      agree no_plgs_id
#          2          4
#
# $YQFB_ECODH
#
# no_id_or_transfer        no_plgs_id
#                 2                 4
#
# $ZAPB_ECODH
#
#      agree no_plgs_id
#          5          1
```
The three metrices you mentioned in your comment from 10th November are easy to calculate:
```r

## metric a: how often identified
fData(ms)$nIdentified <- rowSums(!is.na(exprs(ms)))

## metric b: how often PLGS/synapter agree
fData(ms)$nAgree <- rowSums(fData(ms)[, agreeCol] == "agree")

## metric 3: how often PLGS/synapter disagree
fData(ms)$nDisagree <- rowSums(fData(ms)[, agreeCol] == "disagree")

tail(fData(ms)[, c(agreeCol, TRUE, TRUE, TRUE)])
#            synapterPlgsAgreement.ups25a synapterPlgsAgreement.ups25b synapterPlgsAgreement.ups25c synapterPlgsAgreement.ups50a
# YEJL_ECODH                   no_plgs_id                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YFBU_ECODH                        agree                        agree                        agree                        agree
# YGFZ_ECODH                        agree                        agree                        agree                        agree
# YJGA_ECODH                        agree                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer                   no_plgs_id                   no_plgs_id
# ZAPB_ECODH                        agree                        agree                        agree                        agree
#            synapterPlgsAgreement.ups50b synapterPlgsAgreement.ups50c nIdentified nAgree nDisagree
# YEJL_ECODH                   no_plgs_id                   no_plgs_id           6      0         0
# YFBU_ECODH                        agree                        agree           6      6         0
# YGFZ_ECODH                        agree                        agree           6      6         0
# YJGA_ECODH                        agree                   no_plgs_id           6      2         0
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer           4      0         0
# ZAPB_ECODH                   no_plgs_id                        agree           6      5         0
```
@pavel-shliaha Are these metrices enough? If you satisfied with these results I will write a little function to calculate and add them to the `MSnSet` object.

**Comment by sgibb** [comment]
Would it be enough to have a single column `synapterPlgsAgreementRatio` that contains the number of `agree` vs number of `identified` (metric b divided by metric c; last column):
```r
fData(ms)$synapterPlgAgreementRatio <- fData(ms)$nAgree/fData(ms)$nIdentified
tail(fData(ms)[, c(agreeCol, TRUE, TRUE, TRUE, TRUE)])
#            synapterPlgsAgreement.ups25a synapterPlgsAgreement.ups25b synapterPlgsAgreement.ups25c synapterPlgsAgreement.ups50a
# YEJL_ECODH                   no_plgs_id                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YFBU_ECODH                        agree                        agree                        agree                        agree
# YGFZ_ECODH                        agree                        agree                        agree                        agree
# YJGA_ECODH                        agree                   no_plgs_id                   no_plgs_id                   no_plgs_id
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer                   no_plgs_id                   no_plgs_id
# ZAPB_ECODH                        agree                        agree                        agree                        agree
#            synapterPlgsAgreement.ups50b synapterPlgsAgreement.ups50c nIdentified nAgree nDisagree synapterPlgAgreementRatio
# YEJL_ECODH                   no_plgs_id                   no_plgs_id           6      0         0                 0.0000000
# YFBU_ECODH                        agree                        agree           6      6         0                 1.0000000
# YGFZ_ECODH                        agree                        agree           6      6         0                 1.0000000
# YJGA_ECODH                        agree                   no_plgs_id           6      2         0                 0.3333333
# YQFB_ECODH                   no_plgs_id            no_id_or_transfer           4      0         0                 0.0000000
# ZAPB_ECODH                   no_plgs_id                        agree           6      5         0                 0.8333333
```
With such a column it would be possible to remove all peptides that are not identified in e.g. at least 75% of all runs.

**Comment by pavel-shliaha** [comment]
Thanks Sebastian, just what I wanted.

**Comment by sgibb** [comment]
See https://github.com/lgatto/synapter/issues/39#issuecomment-89670957 for an example using the latest synapter@saturation branch.

TODO:
- There is not any documentation of this functions yet (no vignette; not even a manual page).
- We have to rethink about the new function/column/argument names.
- The function should be a method.

**Comment by pavel-shliaha** [comment]
Two things that need to be changed about the function:

1) I can see some NA values in nAgree and nDisagree columns. This should not be the case
2) as far as I understand at the moment the synapterPlgsAgreementRatio column is computed as nAgree/nIdentified. E.g. 

                            nIdentified nAgree nDisagree synapterPlgsAgreementRatio
IGENEPSEHSIHENAYGLAR                 17     15         0                  0.8823529

15/17 = 0.882

what we actually should be doing is computing it as nAgree/ (nAgree + nDisagree). In this case 15/ (15 + 0) = 1

**Comment by sgibb** [comment]
Why should we use `nAgree + nDisagree` instead of `nIdentified` as denominator? `nIdentified` would be the same as `nAgree + nDisagree` for all EMRTs but the ones that are matched by synapter or PLGS exclusively. Given the above example we would get an `AgreementRatio` of 1 (=100%) but synapter just matched 15 out of 17 EMRTs (or found 2 more than PLGS), so the overall consensus is just 15/17.

**Comment by sgibb** [comment]
`NA` values in `nAgree/nDisagree` should not occur anymore.

**Comment by pavel-shliaha** [comment]
can be closed
