### ISSUE TITLE
Cleanup NEWS file.

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#79]
The [2.0](https://github.com/lgatto/synapter/milestones/2.0) version of synapter introduces many new features. Because of the long development process the `NEWS` file is cluttered (there are some entries for features that are removed/replaced in the process).

**Comment by sgibb** [comment]
@lgatto do you prefer a different NEWS format for synapter as well (c.f. MSnbase/NEWS.md)?

**Comment by lgatto** [comment]
Yes, so that the news are displayed properly when we create a `pkgdown` site for the package.

**Comment by sgibb** [comment]
done: https://github.com/lgatto/synapter/blob/2.0/NEWS.md
