### ISSUE TITLE
`filterUniqueMatches` needs to remove Pep3D data

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#85]
The current implementation of `filterUniqueMatches` doesn't remove EMRTs but sets the `Function` column to `-1` (same for `filterNonUniqueMatches`, `Function == -2`). If we use `as(synapterAnalysis, "MSnSet")` these filtered EMRTs and their counts are added to the MSnSet object. That's why we have to replace all Pep3D related data (Counts etc) with `NA`. Or we exclude all EMRTs with `Function < 0` from the conversion to MSnSet.

CC: @pavel-shliaha

**Comment by lgatto** [comment]
I would suggest to keep these data points with `NA`, because `as` should only convert the data without additional filtering.

**Comment by sgibb** [comment]
That sounds reasonable to me but @pavel-shliaha asked me not to remove any information from the MatchedEMRTs data.frame. If @pavel-shliaha agree I will modify `filterUniqueMatches` to set the Pep3D related data (Counts etc) of the filtered EMRTs to `NA`.

**Comment by sgibb** [comment]
To clarify the problem I add a little code sample:
```r
# normal synapter + fragment matching workflow
# ...
filterNonUniqueMatches(s, minDelta=2)

emrts <- s$MatchedEMRTs

## find non-unique matches that are filtered and mark them with -0.01
i <- which(emrts$Function.2 > 1 & emrts$Function == -emrts$Function.2)
s$MatchedEMRTs[i, "Counts"] <- -0.01

## convert Synapter object into a MSnSet
m <- as(s, "MSnSet")

head(tail(exprs(m), 40), 10)
#                  Synapter1
# MYDEVLK                 NA
# IAGYVMDNR          1970.00
# LIEFDLNTVK         2935.00
# ATLEK             21603.00
# LAFLESTHDK         3911.00
# YLNAMESIGNK          -0.01   <-- should be NA
# NYDIELENFK         1195.00
# IANVQSQLEK         1990.00
# TLAFLIPAIELLHSLK        NA
# NILQESVLNK         1659.00
```
As mentioned above IMHO the only solution would be to replace all Pep3D data by `NA` for all filtered values (or remove the completely but this would distort the resulting MSnSet).

**Comment by sgibb** [comment]
(Sry, I have removed the previous posted code example because it was completely useless and wrong.)
To clarify the problem I add a little code sample:
```r
# normal synapter + fragment matching workflow
# ...
filterNonUniqueMatches(s, minDelta=2)

# find all non-unique matches that were filtered
i <- which(s$MatchedEMRTs$Function.2 > 1 &
           s$MatchedEMRTs$Function == -MatchedEMRTs$Function.2)

## convert Synapter object into a MSnSet
m <- as(s, "MSnSet")

## should all be NA (some are NA because there were "transfered" and have no Pep3D data at all)
exprs(m)[i]
#  [1]    NA  6570  4245    NA 11544  1039    NA  3059   819  1896    NA  3086    NA  2058 10124
# [16]  2630  5871    NA  1383 98406  4438    NA  1473  3876  1205    NA    NA    NA   855 16689
# [31]    NA    NA    NA    NA  3823    NA  1242    NA    NA    NA    NA  2450    NA    NA    NA
# [46]    NA    NA    NA
```
As mentioned above IMHO the only solution would be to replace all Pep3D data by `NA` for all filtered values (or remove the completely but this would distort the resulting MSnSet).

**Comment by pavel-shliaha** [comment]
It is ok to make the counts as NA values, after the additional filter on fragment number has been applied.
