### ISSUE TITLE
export Fragments/Spectra to MGF

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#89]
Because the `final_fragment.csv` and `Spectrum.xml` files are imported into an `MSnExp` object it should be simple. Unfortunately it is not.
```r
export2mgf <- function(synapterObj, file, 
                       what = c("identfragments", "quantspectra")) {
  what <- match.arg(what)

  switch(what,
         "identfragments" = writeMgfData(synapterObj$IdentFragmentData, 
                                         con = file),
         "quantspectra" = writeMgfData(synapterObj$QuantSpectrumData, 
                                         con = file))
}
```
```r
export2mgf(s, "file.mgf")
# Error in if (!is.na(sp@precursorCharge)) buffer <- c(buffer, paste("CHARGE=",  :
# argument is of length zero
```

Needs some more investigation (and maybe some adaption of `MSnbase::writeMgfData`).

**Comment by sgibb** [comment]
I am wondering whether it would be better to provide accessors for the spectra/fragment data, e.g. `getIdentificationFragments`, `getQuantitationSpectra` instead of an export function. This would have the advantage that we could use all methods that `MSnbase` provides for `MSnExp` objects.
@pavel-shliaha What do you think?

In this case the user has to call: `writeMgfData(getIdentificationsFragments(synapterObj)), "fragments.mgf")`

**Comment by lgatto** [comment]
+1

**Comment by sgibb** [comment]
Both accessors `getIdentificationFragments` and `getQuantitationSpectra` added.
