### ISSUE TITLE
Confusing names

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#94]
The following names need to be changed to make synapter output easier to understand:

Function
Function.1
Function.2

**Comment by sgibb** [comment]
Which name(s) do you suggest?

`matchedEMRTs`
`matchedEMRTs.beforeFilterUniqueMatches`
`matchedEMRTs.beforeFilterNonUniqueMatches`

**Comment by sgibb** [comment]
duplicate of #67
